# Generated by Django 4.1.1 on 2022-10-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
                ('created_in', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
